######################################################
#
# 
# 
######################################################

# General options:
general:
    author_name: Felix O'Farrell
    project_name: UKBB Pipe
    licence:
    version: 1.0

# Pipeline specific options:

#dir of UKBB files
files: /Users/flixofarrell/Desktop/test_files/small

#title of GRM directory (made by pipeline)
GRM_dir: GRMs

#dir of GCTA64 command 
gcta_dir: gcta/gcta64

pheno: /Users/flixofarrell/Desktop/test_files/small/phe_n.phen

part: 3

