######################################################
#
# YAML file to config parameters 
# 
######################################################

# General options:
general:
    author_name: Felix O'Farrell
    project_name: UKBB Pipe
    licence:
    version: 1.0

# Pipeline specific options:

#dir of UKBB files
files: test_files


#dir of GCTA64 command 
gcta_dir: ./gcta/gcta64

pheno: test_files/phe_n.phen

part: 3

out_dir: test_files/outdir

