######################################################
#
# YAML file to config parameters 
# 
######################################################

# General options:
general:
    author_name: Felix O'Farrell
    project_name: UKBB Pipe
    licence:
    version: 1.0

# Pipeline specific options:

#dir of UKBB files
files: /Users/flixofarrell/Desktop/test_files/small


#dir of GCTA64 command 
gcta_dir: ./gcta/gcta64

pheno: /Users/flixofarrell/Desktop/test_files/small/phe_n.phen

part: 3

out_dir: /Users/flixofarrell/Desktop/outdir

